name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kodenya
        uses: actions/checkout@v4

      - name: Siapkan Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Beri izin untuk menjalankan Gradle
        run: chmod +x gradlew

      - name: Rakit menjadi APK (Debug)
        run: ./gradlew assembleDebug

      - name: Simpan dan Sediakan APK untuk Diunduh
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Android-ku
          path: app/build/outputs/apk/debug/app-debug.apk
